spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clevertest?characterEncoding=utf8
    username: ivan
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        highlight_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  #    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true
logging:
  level:
    com.iivanov.cleverdevtestnewsystem: INFO
    reactor.netty.http.client: DEBUG
cron:
  start-import-notes: 0 15 */2 * * *
url-old-system: http://localhost:8081
timeout-millis-requests: 1000